# Generated by Django 5.1.2 on 2024-10-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('rescued_at', models.DateTimeField()),
                ('animal_name', models.CharField(max_length=30)),
                ('animal_race', models.CharField(max_length=100)),
                ('animal_bio', models.TextField()),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='animals/')),
            ],
        ),
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_phoneNum', models.CharField(max_length=50, null=True)),
                ('user_age', models.IntegerField(null=True)),
                ('cep', models.IntegerField(null=True)),
                ('pref_adopt', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_categ', models.CharField(max_length=20)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
