# Generated by Django 5.1.2 on 2024-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_gene',
            field=models.CharField(default='toptop', max_length=30),
        ),
    ]
