# Generated by Django 5.1.2 on 2024-10-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_animal_animal_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='rescued_at',
            field=models.DateField(default=False),
        ),
    ]
