# Generated by Django 5.1.2 on 2024-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_alter_animal_animal_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_gene',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=6),
        ),
    ]
