# Generated by Django 5.1.2 on 2024-10-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_alter_animal_rescued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_bio',
            field=models.TextField(max_length=233),
        ),
    ]
