# Generated by Django 5.1.2 on 2024-10-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0007_alter_animal_animal_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_bio',
            field=models.TextField(max_length=250),
        ),
    ]
